version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: web3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  wildfly:
    build: .

    depends_on:
      - postgres
    ports:
      - "8080:8080"
